version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: docsqa
      POSTGRES_USER: docsqa
      POSTGRES_PASSWORD: docsqa_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docsqa"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    environment:
      - DATABASE_URL=postgresql+psycopg://docsqa:docsqa_password@db:5432/docsqa
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GITHUB_APP_ID=${GITHUB_APP_ID}
      - GITHUB_INSTALLATION_ID=${GITHUB_INSTALLATION_ID}
      - GITHUB_PRIVATE_KEY=${GITHUB_PRIVATE_KEY}
    volumes:
      - repo_data:/data
      - faiss_cache:/app/.cache
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  # Optional: Frontend (would be added later)
  # frontend:
  #   build:
  #     context: ..
  #     dockerfile: docker/Dockerfile.frontend
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend

  # Optional: Redis for caching (if needed)
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data

volumes:
  postgres_data:
  repo_data:
  faiss_cache:
  # redis_data: